env: "local"
app:
  name: "go-hexagonal"
  version: "v0.1.0"
  debug: true
http_server:
  addr: ":3000"
  pprof: false
  default_page_size: 10
  max_page_size: 100
  read_timeout: "60s"
  write_timeout: "60s"
log:
  save_path: "/tmp"
  file_name: "go-hexagonal.log"
  max_size: 512
  max_age: 7
  local_time: true
  compress: false
mysql:
  user: "root"
  password: "mysqlroot"
  host: "localhost"
  port: 3306
  database: "go-hexagonal"
  char_set: "utf8mb4"
  parse_time: true
  time_zone: "Asia%2fShanghai"
  max_idle_conns: 50
  max_open_conns: 100
  max_life_time: "36000s"
  max_idle_time: "3600s"
redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  db: 0
  pool_size: 300
  idle_timeout: 30
  min_idle_conns: 100
postgres:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "123456"
    db_name: "postgres"
    ssl_mode: "disable"
    time_zone: "UTC"
migration_dir: "./tests/postgre/migrations"

